# Generated by Django 3.0.5 on 2021-01-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('title_name', models.CharField(max_length=200)),
                ('image_file', models.ImageField(upload_to='')),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
    ]
